title: Check if the User Successfully Deployed a model with GitHub Actions
internal_name: Check if the User Successfully Deployed a model with GitHub Actions
vendor: azure
runtime: python3.8
memory: 128
timeout: 10
